name: Azure Static Web Apps CI/CD

on:
  schedule:
    - cron: '0 21 * * *' 
    # Executa todos os dias às 21:00

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      # 1) Baixa o código para o ambiente de execução.
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # 2) Usa o token secret para autenticar no Azure e atualiza o conteúdo estático hospedado na Azure Static Web App.
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_CLIFF_0D55B3310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/web" 
          api_location: "" 
          output_location: "."

  # Ajuda a limpar recursos temporários no Azure Static Web Apps.
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_CLIFF_0D55B3310 }}
          action: "close"
