name: Pipeline branch Main

on:
  schedule:
    - cron: '0 21 * * *'    # Executa todos os dias às 21:00
  push:
    branches:
      - main



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1) Baixa o código para o ambiente de execução.
    - name: Checkout do código
      uses: actions/checkout@v3

    # 2) Baixa e instala a versão 8.0 do .NET SDK.
    - name: Instalar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    # 3) Executa dotnet restore no projeto para baixar pacotes necessários.
    - name: Restaurar dependências
      run: dotnet restore pipeline.csproj

    # 4) Roda o dotnet build
    - name: Construir com dotnet
      run: dotnet build --configuration Release

    # 5) Executa migrações no banco SUPABASE
    - name: Executar as migrações
      env:
          CONNECTION_STRING: ${{ secrets.MAIN_DB_URL }} 
      run: dotnet run --project pipeline.csproj

    # 6) Usa o token secret para autenticar no Azure e atualiza o conteúdo estático hospedado na Azure Static Web App.
    - name: Deploy para Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_CLIFF_0D55B3310 }}
        app_location: "/web"
        output_location: "/"
        api_location: ""
        action: "upload"
